apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: agnosticvrepos.gpte.example.com
spec:
  group: gpte.example.com
  names:
    kind: AgnosticVRepo
    listKind: AgnosticVRepoList
    plural: agnosticvrepos
    singular: agnosticvrepo
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
