kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agnosticv-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: agnosticv-operator
  namespace: agnosticv-operator
roleRef:
  kind: ClusterRole
  name: agnosticv-operator
  apiGroup: rbac.authorization.k8s.io
