apiVersion: apps/v1
kind: Deployment
metadata:
  name: agnosticv-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: agnosticv-operator
  template:
    metadata:
      labels:
        name: agnosticv-operator
    spec:
      serviceAccountName: agnosticv-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: quay.io/gpte-devops-automation/agnosticv-operator:v0.0.1
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: quay.io/gpte-devops-automation/agnosticv-operator:v0.0.1
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "agnosticv-operator"
      volumes:
        - name: runner
          emptyDir: {}
