apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: agnosticv-operator
rules:
  - apiGroups:
    - ""
    - template.openshift.io
    resources:
    - templates
    verbs:
      - '*'
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    verbs:
    - '*'
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
  - apiGroups:
    - apps
    resourceNames:
    - agnosticv-operator
    resources:
    - deployments/finalizers
    verbs:
    - update
  - apiGroups:
    - gpte.example.com
    resources:
    - '*'
    verbs:
    - '*'
