---
- debug:
    msg: |
      {{ repo_path }} > {{ account }} > {{ catalog_item }} > {{ stage }}

- include_tasks: include_vars.yml

- name: Create output_dir directory
  file:
    state: directory
    path: "{{ output_dir }}"

- set_fact:
    catalog_item_name: "{{ account | replace('_', '-') }}.{{ catalog_item | lower | regex_replace('_', '-') }}.{{ stage }}"

- name: Generate Catalog item
  template:
    src: catalog_item.yml.j2
    dest: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}.yml"
  vars:
    _name: "{{ catalog_item_name }}"

- name: Generate Catalog item governor
  template:
    src: governor.yaml.j2
    dest: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}_governor.yml"
  vars:
    _name: "{{ catalog_item_name }}"

- set_fact:
    _namespace: "agnosticv-operator"

- name: Use namespace defined in the catalog item YAML
  set_fact:
    _namespace: "{{ merged_vars.agnosticv_meta.catalog_namespace }}"
  when:
    - '"agnosticv_meta" in merged_vars'
    - '"catalog_namespace" in merged_vars.agnosticv_meta'
    - merged_vars.agnosticv_meta.catalog_namespace != ''

- name: Create Namespace
  k8s:
    name: "{{ _namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Delete OpenShift template object
  k8s:
    state: absent
    src: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}.yml"
    namespace: "{{ _namespace }}"

- name: Create OpenShift template object
  k8s:
    state: present
    src: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}.yml"
    namespace: "{{ _namespace }}"

- name: Delete OpenShift Governor object
  k8s:
    state: absent
    src: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}_governor.yml"

- name: Create OpenShift Governor object
  k8s:
    state: present
    src: "{{ output_dir }}/{{ account }}_{{ catalog_item }}_{{ stage }}_governor.yml"
